name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -project "RNGTool.xcodeproj/" -destination "generic/platform=macOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
    - name: Pack Build Files
      run: |
        mkdir ~/RNGTool-latest
        mv build/Release/RNGTool.app ~/RNGTool
    - name: Publish Build Files
      uses: actions/upload-artifact@v2
      with:
        path: ~/RNGTool-latest
        name: RNGTool-latest
