name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get Tools
      run: |
        brew update && \
        brew install create-dmg
    - name: Build
      id: build
      run: |
        xcode-select --switch /Applications/Xcode_16.2.app
        xcodebuild -project "RNGTool.xcodeproj/" -destination "generic/platform=macOS" -configuration Debug build CODE_SIGNING_ALLOWED=NO
    - name: Package DMG
      run: |
        mkdir Packaging/source_folder
        mv build/Debug/RNGTool.app Packaging/source_folder
        cd Packaging/
        chmod +x create-dmg.sh
        ./create-dmg.sh
    - name: Publish Build Files
      uses: actions/upload-artifact@v4
      with:
        path: Packaging/RNGTool-Installer.dmg
        name: RNGTool-Installer-latest.dmg

  build-ios:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build for iOS
      id: build-ios
      run: |
        xcode-select --switch /Applications/Xcode_16.2.app
        xcodebuild -project "RNGTool.xcodeproj/" -target "RNGTool Mobile" -destination "generic/platform=iOS" -configuration Debug build CODE_SIGNING_ALLOWED=NO
    - name: Prepare Files and Create IPA File
      run: |
        mkdir ~/RNGToolMobile
        mkdir ~/RNGToolMobile/Payload
        mv build/Debug-iphoneos/RNGTool.app ~/RNGToolMobile/Payload
        cp Packaging/iTunesArtwork ~/RNGToolMobile/iTunesArtwork
        cd ~/RNGToolMobile/
        zip -r RNGTool.zip *
        mv RNGTool.zip ~/RNGTool.ipa
    - name: Publish Build Files
      uses: actions/upload-artifact@v4
      with:
        path: ~/RNGTool.ipa
        name: RNGTool-latest.ipa
