name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Get Tools
      run: |
        brew update && \
        brew install create-dmg
    - name: Build
      run: xcodebuild -project "RNGTool.xcodeproj/" -destination "generic/platform=macOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
    - name: Download and Prepare DMG Kit
      run: |
        curl https://cdn.ncxprogramming.com/file/software/mac/RNGToolDMGKit.zip --output ~/RNGToolDMGKit.zip
        unzip ~/RNGToolDMGKit.zip -d ~/RNGToolDMGKit/
        mkdir ~/RNGToolDMGKit/RNGTool
        mv build/Release/RNGTool.app ~/RNGToolDMGKit/RNGTool
    - name: Build DMG From Kit
      run: |
        cd ~/RNGToolDMGKit/RNGTool
        ./../create-dmg.sh
    - name: Publish Build Files
      uses: actions/upload-artifact@v2
      with:
        path: ~/RNGToolDMGKit/RNGTool/RNGTool-Installer.dmg
        name: RNGTool-Installer-latest.dmg
    - name: Generate DMG Checksums
      run: |
        mkdir ~/RNGTool-Checksums
        shasum -a 256 ~/RNGToolDMGKit/RNGTool/RNGTool-Installer.dmg | sed 's/ .*//g' > ~/RNGTool-Checksums/RNGTool-Installer.dmg.sha256
        openssl md5 ~/RNGToolDMGKit/RNGTool/RNGTool-Installer.dmg | sed 's/.* //' > ~/RNGTool-Checksums/RNGTool-Installer.dmg.md5
    - name: Publish DMG Checksums
      uses: actions/upload-artifact@v2
      with:
        path: ~/RNGTool-Checksums/*
        name: RNGTool-Checksums
