name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -project RNGTool.xcodeproj/
    - name: Pack Build Files
      run: |
        mkdir ~/RNGTool
        mv build/Release/RNGTool.app ~/RNGTool
    - name: Publish Build Files
      uses: actions/upload-artifact@v2
      with:
        path: ~/RNGTool/RNGTool.app
        name: RNGTool-latest
